//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CincoEnLinea.Recursos_Internacionalización {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CincoEnLinea.Recursos_Internacionalización.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        internal static string bRegresar {
            get {
                return ResourceManager.GetString("bRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empatadas.
        /// </summary>
        internal static string colEmpatadas {
            get {
                return ResourceManager.GetString("colEmpatadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganadas.
        /// </summary>
        internal static string colGanadas {
            get {
                return ResourceManager.GetString("colGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perdidas.
        /// </summary>
        internal static string colPerdidas {
            get {
                return ResourceManager.GetString("colPerdidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición.
        /// </summary>
        internal static string colPosicion {
            get {
                return ResourceManager.GetString("colPosicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string colUsuario {
            get {
                return ResourceManager.GetString("colUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Durante su turno cada jugador elige una casilla vacía y coloca su ficha en ella.
        /// </summary>
        internal static string labelRegla1 {
            get {
                return ResourceManager.GetString("labelRegla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gana el jugador que logre poner 5 fichas en línea vertical, horizontal o diagonal.
        /// </summary>
        internal static string labelRegla2 {
            get {
                return ResourceManager.GetString("labelRegla2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si el tablero se llena de fichas se declara empate.
        /// </summary>
        internal static string labelRegla3 {
            get {
                return ResourceManager.GetString("labelRegla3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si se abandona la partida se registra como partida perdida.
        /// </summary>
        internal static string labelRegla4 {
            get {
                return ResourceManager.GetString("labelRegla4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejores Jugadores.
        /// </summary>
        internal static string WindowTitleMejoresJugadores {
            get {
                return ResourceManager.GetString("WindowTitleMejoresJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver reglas.
        /// </summary>
        internal static string WindowTitleVerReglas {
            get {
                return ResourceManager.GetString("WindowTitleVerReglas", resourceCulture);
            }
        }
    }
}
