//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CincoEnLinea.RecursosInternacionalizacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IniciarSesionRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IniciarSesionRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CincoEnLinea.RecursosInternacionalizacion.IniciarSesionRes", typeof(IniciarSesionRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        internal static string buttonEntrar {
            get {
                return ResourceManager.GetString("buttonEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltaron campos por llenar, no seas así.
        /// </summary>
        internal static string camposVacios {
            get {
                return ResourceManager.GetString("camposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña está mal, intenta de nuevo.
        /// </summary>
        internal static string contrasenaIncorrecta {
            get {
                return ResourceManager.GetString("contrasenaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desarrolladores:.
        /// </summary>
        internal static string Desarrolladores {
            get {
                return ResourceManager.GetString("Desarrolladores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tuvimos un problema con la base de datos, inténtalo más tarde.
        /// </summary>
        internal static string excepcionBD {
            get {
                return ResourceManager.GetString("excepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el servidor, intenta más tarde.
        /// </summary>
        internal static string excepcionServicioWcf {
            get {
                return ResourceManager.GetString("excepcionServicioWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicia Sesión.
        /// </summary>
        internal static string labIniciaSesion {
            get {
                return ResourceManager.GetString("labIniciaSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes cuenta?.
        /// </summary>
        internal static string noCuenta {
            get {
                return ResourceManager.GetString("noCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no está registrado.
        /// </summary>
        internal static string noRegistrado {
            get {
                return ResourceManager.GetString("noRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrate.
        /// </summary>
        internal static string registrar {
            get {
                return ResourceManager.GetString("registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la base de datos.
        /// </summary>
        internal static string tituloExcepcionBD {
            get {
                return ResourceManager.GetString("tituloExcepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en servidor.
        /// </summary>
        internal static string tituloExcepcionWcf {
            get {
                return ResourceManager.GetString("tituloExcepcionWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pequeño problema.
        /// </summary>
        internal static string tituloMensajeContrasena {
            get {
                return ResourceManager.GetString("tituloMensajeContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se permiten letras, números, guión medio(-) y guión bajo.
        /// </summary>
        internal static string toolTip {
            get {
                return ResourceManager.GetString("toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string wTIniciarSesion {
            get {
                return ResourceManager.GetString("wTIniciarSesion", resourceCulture);
            }
        }
    }
}
