//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CincoEnLinea.RecursosInternacionalizacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MesaJuegoRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MesaJuegoRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CincoEnLinea.RecursosInternacionalizacion.MesaJuegoRes", typeof(MesaJuegoRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar partida.
        /// </summary>
        internal static string botonAbandonaPartida {
            get {
                return ResourceManager.GetString("botonAbandonaPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas salir?.
        /// </summary>
        internal static string confirmacionSalida {
            get {
                return ResourceManager.GetString("confirmacionSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tuvimos un problema con la base de datos, inténtalo más tarde.
        /// </summary>
        internal static string excepcionBD {
            get {
                return ResourceManager.GetString("excepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el servidor, intenta más tarde.
        /// </summary>
        internal static string excepcionServicioWcf {
            get {
                return ResourceManager.GetString("excepcionServicioWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno de.
        /// </summary>
        internal static string labelTurno {
            get {
                return ResourceManager.GetString("labelTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ups, partida empatada.
        /// </summary>
        internal static string mensajeEmpatar {
            get {
                return ResourceManager.GetString("mensajeEmpatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Ganaste! Tu abuelita va a estar orgullosa.
        /// </summary>
        internal static string mensajeGanar {
            get {
                return ResourceManager.GetString("mensajeGanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es tu turno.
        /// </summary>
        internal static string mensajeNoTurno {
            get {
                return ResourceManager.GetString("mensajeNoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No lo creo, has perdido.
        /// </summary>
        internal static string mensajePerder {
            get {
                return ResourceManager.GetString("mensajePerder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Miedo?.
        /// </summary>
        internal static string tituloConfirmacion {
            get {
                return ResourceManager.GetString("tituloConfirmacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿En serio?.
        /// </summary>
        internal static string tituloEmpatar {
            get {
                return ResourceManager.GetString("tituloEmpatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la base de datos.
        /// </summary>
        internal static string tituloExcepcionBD {
            get {
                return ResourceManager.GetString("tituloExcepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en servidor.
        /// </summary>
        internal static string tituloExcepcionWcf {
            get {
                return ResourceManager.GetString("tituloExcepcionWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ganador.
        /// </summary>
        internal static string tituloGanar {
            get {
                return ResourceManager.GetString("tituloGanar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aun no.
        /// </summary>
        internal static string tituloNoTurno {
            get {
                return ResourceManager.GetString("tituloNoTurno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derrotado.
        /// </summary>
        internal static string tituloPerder {
            get {
                return ResourceManager.GetString("tituloPerder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        internal static string tituloVentana {
            get {
                return ResourceManager.GetString("tituloVentana", resourceCulture);
            }
        }
    }
}
