//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CincoEnLinea.RecursosInternacionalizacion {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegistroRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegistroRes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CincoEnLinea.RecursosInternacionalizacion.RegistroRes", typeof(RegistroRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regístrame.
        /// </summary>
        internal static string bRegistro {
            get {
                return ResourceManager.GetString("bRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresar.
        /// </summary>
        internal static string bRegresar {
            get {
                return ResourceManager.GetString("bRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay campos vacíos, intenta de nuevo.
        /// </summary>
        internal static string camposVacios {
            get {
                return ResourceManager.GetString("camposVacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Por qué eres así?.
        /// </summary>
        internal static string camposVaciosTitulo {
            get {
                return ResourceManager.GetString("camposVaciosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma la contraseña.
        /// </summary>
        internal static string confirmaContrasena {
            get {
                return ResourceManager.GetString("confirmaContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string contrasena {
            get {
                return ResourceManager.GetString("contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas deben ser iguales, amiguito.
        /// </summary>
        internal static string contrasenaInvalida {
            get {
                return ResourceManager.GetString("contrasenaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Qué pasó amiguito?.
        /// </summary>
        internal static string contrasenaInvalidaTitulo {
            get {
                return ResourceManager.GetString("contrasenaInvalidaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algo salió mal, intenta de nuevo.
        /// </summary>
        internal static string excepcionBD {
            get {
                return ResourceManager.GetString("excepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tuvimos problemas al conectarnos, intenta más tarde.
        /// </summary>
        internal static string excepcionServicioWcf {
            get {
                return ResourceManager.GetString("excepcionServicioWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza a jugar.
        /// </summary>
        internal static string labComienzaJugar {
            get {
                return ResourceManager.GetString("labComienzaJugar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        internal static string nombreUsuario {
            get {
                return ResourceManager.GetString("nombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡A jugar, padrino!.
        /// </summary>
        internal static string registroExitoso {
            get {
                return ResourceManager.GetString("registroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro exitoso.
        /// </summary>
        internal static string registroExitosoTitulo {
            get {
                return ResourceManager.GetString("registroExitosoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en base de datos.
        /// </summary>
        internal static string tituloExcepcionBD {
            get {
                return ResourceManager.GetString("tituloExcepcionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en servidor.
        /// </summary>
        internal static string tituloExcepcionWcf {
            get {
                return ResourceManager.GetString("tituloExcepcionWcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sólo se permiten letras, números, guión medio(-) y guión bajo.
        /// </summary>
        internal static string toolTip {
            get {
                return ResourceManager.GetString("toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay un usuario registrado con ese nombre.
        /// </summary>
        internal static string usuarioRepetido {
            get {
                return ResourceManager.GetString("usuarioRepetido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Qué incómodo!.
        /// </summary>
        internal static string usuarioRepetidoTitulo {
            get {
                return ResourceManager.GetString("usuarioRepetidoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string wTRegistro {
            get {
                return ResourceManager.GetString("wTRegistro", resourceCulture);
            }
        }
    }
}
