//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CincoEnLinea.Recursos_Internacionalización {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CincoEnLinea.Recursos_Internacionalización.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jugadores.
        /// </summary>
        internal static string botonJugadores {
            get {
                return ResourceManager.GetString("botonJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reglas.
        /// </summary>
        internal static string botonReglas {
            get {
                return ResourceManager.GetString("botonReglas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablero.
        /// </summary>
        internal static string botonTablero {
            get {
                return ResourceManager.GetString("botonTablero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regresar.
        /// </summary>
        internal static string bRegresar {
            get {
                return ResourceManager.GetString("bRegresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        internal static string butttonEntrar {
            get {
                return ResourceManager.GetString("butttonEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empatadas.
        /// </summary>
        internal static string colEmpatadas {
            get {
                return ResourceManager.GetString("colEmpatadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ganadas.
        /// </summary>
        internal static string colGanadas {
            get {
                return ResourceManager.GetString("colGanadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdidas.
        /// </summary>
        internal static string colPerdidas {
            get {
                return ResourceManager.GetString("colPerdidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posición.
        /// </summary>
        internal static string colPosicion {
            get {
                return ResourceManager.GetString("colPosicion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string colUsuario {
            get {
                return ResourceManager.GetString("colUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Sesión.
        /// </summary>
        internal static string gBoxIniciarSesion {
            get {
                return ResourceManager.GetString("gBoxIniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No tienes cuenta?.
        /// </summary>
        internal static string labelNoTienesCuenta {
            get {
                return ResourceManager.GetString("labelNoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durante su turno cada jugador elige una casilla vacía y coloca su ficha en ella.
        /// </summary>
        internal static string labelRegla1 {
            get {
                return ResourceManager.GetString("labelRegla1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gana el jugador que logre poner 5 fichas en línea vertical, horizontal o diagonal.
        /// </summary>
        internal static string labelRegla2 {
            get {
                return ResourceManager.GetString("labelRegla2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si el tablero se llena de fichas se declara empate.
        /// </summary>
        internal static string labelRegla3 {
            get {
                return ResourceManager.GetString("labelRegla3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si se abandona la partida se registra como partida perdida.
        /// </summary>
        internal static string labelRegla4 {
            get {
                return ResourceManager.GetString("labelRegla4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regístrate.
        /// </summary>
        internal static string linkLabelRegistrate {
            get {
                return ResourceManager.GetString("linkLabelRegistrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario.
        /// </summary>
        internal static string textBoxUsuario {
            get {
                return ResourceManager.GetString("textBoxUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mejores Jugadores.
        /// </summary>
        internal static string WindowTitleMejoresJugadores {
            get {
                return ResourceManager.GetString("WindowTitleMejoresJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver reglas.
        /// </summary>
        internal static string WindowTitleVerReglas {
            get {
                return ResourceManager.GetString("WindowTitleVerReglas", resourceCulture);
            }
        }
    }
}
